;GNU ED CLONE FOR NORTHSTAR DISK OPERATING SYSTEM
;REFERENCES FILE 'NSDOS-PROC.ASM' FOR MANY OS CALLS AND CONSTANTS
;
;SAGE I HENDRICKS
;2023 NOV 10

	ORG	TPA
MAIN:
	CALL	CONARG		;GET FILENAME FROM CONSOLE ARGUEMENTS
	CALL	DOS		;RETURN CONTROL TO DOS/EXIT
	HLT			;IF EXIT FAILS, HALT THE SYSTEM

*GET FILENAME FROM CONSOLE ARG LIST
CONARG:
	RET
	END
