;NORTHSTAR DISK OPERATING SYSTEM PROCEDURES/ROUTINES
;AND OTHER CONSTANTS.
;
;NORTHSTAR DOS VERSION 2
;
;SAGE I HENDRICKS
;2023 NOV 10

TPA	EQU	0	;TRANSIENT PROGRAM AREA

COUT	EQU	0	;CHARACTER OUTPUT 
CIN	EQU	0	;CHARACTER INPUT 
TINIT	EQU	0	;TERMINAL INITIALIZATION 
CONTC	EQU	0	;CHECK FOR CONTROL-C
HDERR	EQU	0	;HARD DISK ERROR
DLOOK	EQU	0	;FILE DIRECTORY LOOKUP
DWRIT	EQU	0	;DIRECTORY ENTRY TO DISK WRITE
DCOM	EQU	0	;FILE IO COMMAND
LIST	EQU	0	;LIST FILE DIRECTORY
DOS	EQU	0	;DOS ENTRY-POINT

DUNITN	EQU	001[CH	;DEFAULT UNIT NUMBER (FLOPPY MAYBE?)

WRITE	EQU	000H	;DCOM WRITE COMMAND
READ	EQU	001H	;DCOM READ COMMAND
VERIFY	EQU	002H	;DCOM VERIFY COMMAND
